<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>363569b3-fb8b-4bf5-ba54-2cb3365ed7d3</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.NodeJs" Version="9.*" />
    <ProjectReference Include="..\GateMonitor.Blazor\GateMonitor.Blazor.csproj" />
  </ItemGroup>

</Project>
