name: dotNet Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  dotnet-build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.x

    - name: Install dependencies
      run: dotnet restore .\dotNet

    - name: Build
      run: dotnet build ./dotNet --no-restore

    - name: Test
      run: dotnet test ./dotNet --no-restore --verbosity normal --logger trx --collect:"XPlat Code Coverage" --no-build
    
    - name: Test Pack nuget
      run: |
         dotnet pack ./dotNet --no-build --no-restore --include-symbols --verbosity normal 
      
